Repository spryker-sdk/sdk-contracts, pull requests merged in 2022-10, with the labels that each got.

#30 Correct misspelled words
  src/Entity/PlaceholderInterface.php
  src/Entity/SettingInterface.php
  src/Entity/TaskInterface.php
  src/Report/ReportArrayConverterInterface.php
  src/Report/Violation/ViolationInterface.php
  src/Report/Violation/ViolationReportArrayConverterInterface.php
  src/Setting/SettingInitializerInterface.php
  src/ValueResolver/ValueResolverInterface.php
Labels: merge-only

#31 SDK-1007: Added enum consts for the entities
  src/Enum/Lifecycle.php
  src/Enum/Setting.php
  src/Enum/Task.php
  src/Enum/ValueTypeEnum.php
Labels: dev-qa done

#28 SDK-848 add SettingInitializerInterface method
  src/Setting/SettingInitializerInterface.php
Labels: ready-for-release
